import fs from 'fs';
import path from 'path';

console.log('Starting model embedding...');

const modelDir = './data_scraper/saved-model';
const outputDir = './'; // Output to the root project folder

// 1. Read the model.json file
const modelJsonPath = path.join(modelDir, 'model.json');
const modelJson = JSON.parse(fs.readFileSync(modelJsonPath, 'utf-8'));

// 2. Read the binary weights file
const weightsBinPath = path.join(modelDir, 'weights.bin');
const weightsBin = fs.readFileSync(weightsBinPath);

// 3. Convert binary weights to a JavaScript-friendly format (a byte array)
const weightsArray = new Uint8Array(weightsBin);

// 4. Create the TypeScript file content
const tsContent = `
// This file is auto-generated by embed-model.js. Do not edit.

export const modelJson = ${JSON.stringify(modelJson)};
export const modelWeights = new Uint8Array([${weightsArray.toString()}]);
`;

// 5. Write the new TypeScript file
const outputPath = path.join(outputDir, 'embedded-model.ts');
fs.writeFileSync(outputPath, tsContent);

console.log(`✅ Model embedded successfully into ${outputPath}`);